### PR TITLE
Return new tagger instances for each call to get_tagger().

### PR DESCRIPTION
**Pull request by tavianator**
Fixes https://github.com/chokkan/crfsuite/issues/35

### CODE REVIEW

**Comment by usptact** [comment]
The training goes smooth. The tagging not. I get the predictions printed out and (at the end?) it segfaults. Can you please check?

**Comment by tavianator** [comment]
Hmm, this one I can't reproduce.  Can you share your training and tagging command lines?  And possibly the data and/or model?  Thanks!

**Comment by usptact** [comment]
I realized that I tried to patch this branch code with your changes (I noticed that your fork has much more commits). May be I messed up by manually modifying the code. I must check how I copied it.

The command-line arguments are standard: crfsuite tag -m model file.features
The binary built using this repository code tags everything fine.

**Comment by tavianator** [comment]
@chokkan I rebased this to fix the conflict.  Thanks for merging all those PRs by the way!

**Comment by chokkan** [comment]
@tavianator Thank you very much for fixing the conflict. It was very helpful.

**Pull request merged**
