### PR TITLE
Try aligned_alloc() and memalign() in addition to posix_memalign().

### PR DESCRIPTION
**Pull request by tavianator**

### CODE REVIEW

**Comment by kmike** [comment]
I'm trying to update https://github.com/tpeng/python-crfsuite to use your https://github.com/Maluuba/crfsuite repo, but it looks like this change breaks the package (`Symbol not found: _aligned_alloc`). 

python-crfsuite doesn't use automake, relying just on distutils. It also compiles code using C++ compiler because it uses C++ API, not C API.

**Comment by tavianator** [comment]
Just tried it and it works for me on Linux.  What platform are you on?  I'm guessing OS X.  You may be able to work around it with -std=c99 (anything below c11 really).

**Comment by kmike** [comment]
yeah, I'm on OS X

**Comment by kmike** [comment]
It seems -std=c99 workaround doesn't work because compilation is in C++ mode (`invalid argument '-std=c99' not allowed with 'C++/ObjC++'`)

**Comment by tavianator** [comment]
`CFLAGS="-std=c99" pip install .` works fine for me.

What compiler flags do you see by default?  As far as I know C11 isn't the default mode of any major compiler, so there must be something setting it.

The issue is basically that `-std=c11` doesn't magically force the C library to implement the C11 library functions.  There's no direct way to check for those, so I'm just testing  `__STDC_VERSION__` and assuming that nobody sets `-std=c11` on a platform that doesn't fully support it.

**Comment by kmike** [comment]
This is my log:
```
> CFLAGS="-std=c99" pip install .
Processing /Users/kmike/svn/python-crfsuite
  Requirement already satisfied (use --upgrade to upgrade): python-crfsuite==0.8.4 from file:///Users/kmike/svn/python-crfsuite in /Users/kmike/envs/py3-splash/lib/python3.4/site-packages
Building wheels for collected packages: python-crfsuite
  Running setup.py bdist_wheel for python-crfsuite
  Complete output from command /Users/kmike/envs/py3-splash/bin/python3.4 -c "import setuptools;__file__='/var/folders/_5/cbsg50991szfp1r9nwxpx8580000gq/T/pip-nonzxf4p-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/_5/cbsg50991szfp1r9nwxpx8580000gq/T/tmplyzgllj1pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -Icrfsuite/include/ -Icrfsuite/lib/cqdb/include -Iliblbfgs/include -Ipycrfsuite -I/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c pycrfsuite/_pycrfsuite.cpp -o build/temp.macosx-10.10-x86_64-3.4/pycrfsuite/_pycrfsuite.o
  error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
  error: command 'clang' failed with exit status 1
```

**Comment by tavianator** [comment]
Ah okay I can reproduce that with `clang`.

**Comment by cynthia** [comment]
Did the clang compatibility issue ever get fixed? Considering that quite a few of the issues I'm seeing reported are macOS specific - it's not something that we can ignore before merging the PR.

Sorry this took so long to get around to.

**Pull request merged**
