### PR TITLE
Added the option '--marginal-all' and its description to the usage message of tag command.

### PR DESCRIPTION
**Pull request by jlerouge**
I needed an option to show all marginals for my application, and I found it in the source code. But it's neither documented in the help message nor on the website.

### CODE REVIEW

**Comment by usptact** [comment]
Hi,

Did you use this information to find the n-best taggings? If not, what information is needed to get those predictions?

Thanks

**Comment by tavianator** [comment]
@usptact Even all the marginals are not enough to get the n-best taggings.  The Viterbi implementation would have to be changed.

**Comment by usptact** [comment]
@tavianator Thanks for chiming in. I was in doubt whether the marginals are enough to find the n-best taggings. A quick glance on www showed that one of arguably simplest ways would be to use N-Viterbi, which basicaly stores n forward/backward links. I am pretty poor versed in algorithms, especially in clean C, but I will try to find some code which would be easy to use here.

I see this as an additional option in "tag" mode, say "--nbest" which produces n tab delimited columns with label predictions.

**Comment by tavianator** [comment]
@usptact That makes sense.  Actually at some point I do plan to add n-best support to CRFsuite, just haven't found the time.  If you (or anyone) beat me to it that would be great!

**Pull request merged**
