### PR TITLE
Create from memory

### PR DESCRIPTION
**Pull request by tavianator**

### CODE REVIEW

**Comment by kmike** [comment]
see also: https://github.com/chokkan/crfsuite/pull/9

**Comment by tavianator** [comment]
@kmike Huh, guess we should have scrolled down further on the pull requests page before we wrote this :)  I like this version slightly better (`const` in more places, `size_t` vs `int`) but they're very similar.

**Comment by usptact** [comment]
Thank you guys for keeping improving CRFSuite! Really appreciate that! I am using it almost daily to build models and glad to see that the tool is getting updates/fixes. The only sad thing that merges don't get that quickly into the master......

**Comment by kmike** [comment]
Thanks for working on it @tavianator! It is indeed sad PRs are not merged. 
Yeah, #9 is indeed very similar; it had one extra feature - C++ interface was updated as well, but your version looks cleaner.

**Comment by chokkan** [comment]
I do appreciate your efforts for improving CRFsuite and exchanging the useful information. I apologize my late response for pull requests. I will do my best to review the code to integrate it. I will probably work on this in the next weekend as I have a lot of things to be done next week.

Thanks,
Naoaki

**Comment by tavianator** [comment]
@kmike Good point!  We don't use the C++ wrapper, but I'm happy to update it.

@chokkan No worries, thanks for writing CRFsuite!

**Comment by usptact** [comment]
Bump

**Pull request merged**
